# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import texpenses.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('kindDescription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaxOffice',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('kindDescription', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=200, validators=[texpenses.validators.iban_validation])),
                ('taxRegNum', models.IntegerField(primary_key=True, serialize=False, validators=[texpenses.validators.afm_validator])),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texpenses.Account')),
                ('specialtyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texpenses.Specialty')),
                ('taxOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texpenses.TaxOffice')),
            ],
        ),
        migrations.CreateModel(
            name='UserKind',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('kindDescription', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texpenses.UserKind'),
        ),
    ]
