# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-21 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0041_auto_20190201_1417'),
        ('texpenses', '0042_auto_20190129_1352'),
    ]

    operations = [
    ]
