# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-04 14:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import texpenses.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0042_auto_20190129_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TravelFile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[['petition', 'Petition']], max_length=30)),
                ('source_id', models.IntegerField()),
                ('file_content', models.FileField(max_length=1024, upload_to=texpenses.models.models.generate_filename)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('file_name', models.CharField(max_length=1024)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
