# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0042_auto_20190129_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_resend_verification_email',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_reset_password_email',
            field=models.DateTimeField(null=True),
        ),
    ]
