# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-04 14:40
from __future__ import unicode_literals
import os

from django.db import migrations, models
from texpenses.serials import get_serial


def migrate_files(apps, schema_editor):
    Petition = apps.get_model('texpenses', 'Petition')
    TravelFile = apps.get_model('texpenses', 'TravelFile')

    for p in Petition.objects.all():
        tf = p.travel_files
        if tf:
            TravelFile.objects.create(
                id=get_serial('travel_file'),
                owner=p.user,
                source='petition',
                source_id=p.id,
                file_name=os.path.basename(tf.name),
                file_content=tf)


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0043_serials_travelfile'),
    ]

    operations = [
        migrations.RunPython(migrate_files),
    ]
