# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0044_auto_20190204_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='travel_files',
        ),
        migrations.AddField(
            model_name='petition',
            name='travel_files',
            field=models.ManyToManyField(blank=True, to='texpenses.TravelFile'),
        ),
    ]
