# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-27 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0046_auto_20190204_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelfile',
            name='file_kind',
            field=models.CharField(default=b'travel_file', max_length=128),
        ),
    ]
