# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-03 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0047_travelfile_file_kind'),
        ('texpenses', '0043_merge_20190321_0941'),
    ]

    operations = [
    ]
