# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0048_merge_20190603_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resend_verification_blocked_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_email_blocked_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_link_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
