# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0050_kind-payment-way-edyte-change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='additional_expenses_default_currency',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='participation_default_currency',
        ),
        migrations.RemoveField(
            model_name='travelinfo',
            name='accommodation_default_currency',
        ),
        migrations.RemoveField(
            model_name='travelinfo',
            name='transportation_default_currency',
        ),
    ]
