# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-11 11:47
from __future__ import unicode_literals

from django.db import migrations


def initialize_currency_fields(apps, schema_editor):
    TravelInfo = apps.get_model('texpenses', 'TravelInfo')
    for t in TravelInfo.objects.all():
        if t.accommodation_local_currency == '':
            t.accommodation_local_currency = 'EUR'
            t.save()
    Petition = apps.get_model('texpenses', 'Petition')
    for p in Petition.objects.all():
        if p.participation_local_currency == '':
            p.participation_local_currency = 'EUR'
            p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0051_delete-default-currency-fields'),
    ]

    operations = [
        migrations.RunPython(initialize_currency_fields),
    ]
