# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0053_add-EUR-default-value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resend_verification_blocked_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reset_password_email_blocked_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
