# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0054_add-default-value-to-user-times'),
        ('texpenses', '0054_add-max-value-validator-to-quota-field'),
    ]

    operations = [
    ]
