# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-11 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texpenses', '0055_merge_20191120_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='transportation_type',
            field=models.CharField(blank=True, choices=[['EDU', '\u0395\u03ba\u03c0\u03b1\u03af\u03b4\u03b5\u03c5\u03c3\u03b7'], ['MEET', '\u03a3\u03c5\u03bd\u03ac\u03bd\u03c4\u03b7\u03c3\u03b7'], ['OTHER', '\u0386\u03bb\u03bb\u03bf']], max_length=100),
        ),
    ]
