spec = {'.structarray': {'compensation_days_proposed': {'.cli_option': {},
                                                        '.drf_field': {},
                                                        '.field': {},
                                                        '.integer': {},
                                                        '.readonly': {}},
                         'accommodation_payment_description': {'.cli_option':
                                                               {},
                                                               '.drf_field':
                                                               {'allow_blank':
                                                                True,
                                                                'allow_null':
                                                                True,
                                                                'required':
                                                                False},
                                                               '.field': {},
                                                               '.string': {}},

                         'overnights_num_proposed': {'.cli_option': {},
                                                     '.drf_field': {},
                                                     '.field': {},
                                                     '.integer': {},
                                                     '.readonly': {}},
                         'compensation_level': {'.cli_option': {},
                                                '.drf_field': {},
                                                '.field': {},
                                                '.decimal': {'max_digits': 8,
                                                             'decimal_places':3},
                                                '.readonly': {}},
                         'overnight_cost': {'.cli_option': {},
                                            '.drf_field': {},
                                            '.field': {},
                                            '.decimal': {'max_digits': 8,
                                                         'decimal_places':3},
                                            '.readonly': {}},
                         'same_day_return_task': {'.boolean': {},
                                                  '.cli_option': {},
                                                  '.drf_field': {},
                                                  '.field': {},
                                                  '.readonly': {}},
                         'transport_days_proposed': {'.cli_option': {},
                                                     '.drf_field': {},
                                                     '.field': {},
                                                     '.integer': {},
                                                     '.readonly': {}}}}
