spec = {'.structarray': {'arrival_point': {'.cli_option': {},
                                    '.drf_field': {'allow_null': False,
                                                   'required': True},
                                    '.field': {},
                                    '.ref': {'to': 'api/city'}},
                  'departure_point': {'.cli_option': {},
                                      '.drf_field': {'allow_null': False,
                                                     'required': True},
                                      '.field': {},
                                      '.ref': {'to': 'api/city'},
                                      '.required': {}}}}
