FROM node:8
MAINTAINER Antonis Angelakis "angelakis@grnet.gr"

RUN npm install --global yarn
RUN yarn global add bower ember-cli@2.9.1 ember-cli-sass@5.6.0 ember-cli-gen@1.0.16 ember-cli-gen-apimas

ADD ./travelsFront /srv/travel/travelsFront
WORKDIR /srv/travel/travelsFront

RUN yarn install --non-interactive
RUN bower install --allow-root -q
CMD ember build --watch --dev
