version: '2'
services:
        es:
                image: elasticsearch:2.4.0
                ports:
                 - "9200:9200"
                volumes:
                 - ../confs/elastic-2.4.0/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        kibana:
                image: kibana:4.6.4
                ports:
                 - "5601:5601"
                volumes:
                 - ../confs/kibana-4.6.4/kibana.yml:/opt/kibana/config/kibana.yml
                depends_on:
                 - es
                links:
                 - es
        logstash:
                image: logstash:5.4.2
                volumes:
                 - ../confs/logstash-5.4.2:/config-dir
                command: logstash -f /config-dir/travel_expenses.conf
                ports:
                 - "5000:5000"
                depends_on:
                 - es
                links:
                 - es

