spec = {'*': {'additional_expenses': {'.cli_option': {},
                                      '.drf_field': {},
                                      '.field': {},
                                      '.float': {}},
              'additional_expenses_default_currency': {'.cli_option': {},
                                                       '.drf_field': {},
                                                       '.field': {},
                                                       '.string': {}},
              'additional_expenses_description': {'.cli_option': {},
                                                  '.drf_field': {},
                                                  '.field': {},
                                                  '.string': {}},
              'additional_expenses_initial': {'.cli_option': {},
                                              '.drf_field': {},
                                              '.field': {},
                                              '.float': {}},
              'additional_expenses_initial_description': {'.cli_option': {},
                                                          '.drf_field': {},
                                                          '.field': {},
                                                          '.string': {}},
              'additional_expenses_local_currency': {'.cli_option': {},
                                                     '.drf_field': {},
                                                     '.field': {},
                                                     '.string': {}},
              'compensation_decision_date': {'.cli_option': {},
                                             '.date': {},
                                             '.drf_field': {},
                                             '.field': {}},
              'compensation_decision_protocol': {'.cli_option': {},
                                                 '.drf_field': {},
                                                 '.field': {},
                                                 '.string': {}},
              'withdrawn': {'.cli_option': {},
                            '.drf_field': {},
                            '.field': {},
                            '.boolean': {}},
              'compensation_final': {'.cli_option': {},
                                     '.drf_field': {},
                                     '.field': {},
                                     '.float': {},
                                     '.readonly': {}},
              'compensation_petition_date': {'.cli_option': {},
                                             '.date': {},
                                             '.drf_field': {},
                                             '.field': {}},
              'compensation_petition_protocol': {'.cli_option': {},
                                                 '.drf_field': {},
                                                 '.field': {},
                                                 '.string': {}},
              'dse': {'.cli_option': {},
                      '.drf_field': {'allow_null': True, 'required': False},
                      '.field': {},
                      '.integer': {},
                      '.nullable': {},
                      '.readonly': {}},
              'expenditure_date_protocol': {'.cli_option': {},
                                            '.date': {},
                                            '.drf_field': {},
                                            '.field': {},
                                            '.readonly': {}},
              'expenditure_protocol': {'.cli_option': {},
                                       '.drf_field': {},
                                       '.field': {},
                                       '.readonly': {},
                                       '.string': {}},
              'manager_cost_approval': {'.cli_option': {},
                                        '.drf_field': {},
                                        '.field': {},
                                        '.readonly': {},
                                        '.boolean': {}},
              'manager_movement_approval': {'.cli_option': {},
                                          '.drf_field': {},
                                          '.field': {},
                                          '.boolean': {}},
              'timesheeted': {'.cli_option': {},
                              '.drf_field': {'required':False},
                              '.field': {},
                              '.boolean': {}},
              'movement_date_protocol': {'.cli_option': {},
                                         '.date': {},
                                         '.drf_field': {},
                                         '.field': {},
                                         '.readonly': {}},
              'movement_id': {'.cli_option': {},
                              '.drf_field': {},
                              '.field': {},
                              '.readonly': {},
                              '.string': {}},
              'movement_protocol': {'.cli_option': {},
                                    '.drf_field': {},
                                    '.field': {},
                                    '.readonly': {},
                                    '.string': {}},
              'non_grnet_quota': {'.cli_option': {},
                                  '.drf_field': {},
                                  '.field': {},
                                  '.float': {},
                                  '.readonly': {}},
              'overnights_num': {'.cli_option': {},
                                 '.drf_field': {},
                                 '.field': {},
                                 '.integer': {},
                                 '.readonly': {}},
              'compensation_days_num': {'.cli_option': {},
                                 '.drf_field': {},
                                 '.field': {},
                                 '.integer': {},
                                 '.readonly': {}},
              'overnights_proposed': {'.cli_option': {},
                                      '.drf_field': {},
                                      '.field': {},
                                      '.integer': {},
                                      '.readonly': {}},
              'overnights_sum_cost': {'.cli_option': {},
                                      '.drf_field': {},
                                      '.field': {},
                                      '.float': {},
                                      '.readonly': {}},
              'compensation_cost': {'.cli_option': {},
                                      '.drf_field': {},
                                      '.field': {},
                                      '.float': {},
                                      '.readonly': {}},
              'secretary_recommendation': {'.cli_option': {},
                                           '.drf_field': {},
                                           '.field': {},
                                           '.string': {}},
              'task_end_date': {'.cli_option': {},
                                '.datetime': {'format': ['%Y-%m-%dT%H:%M']},
                                '.drf_field': {'required': False},
                                '.field': {},
                                '.readonly': {}},
              'task_start_date': {'.cli_option': {},
                                  '.datetime': {'format': ['%Y-%m-%dT%H:%M']},
                                  '.drf_field': {'required': False},
                                  '.field': {},
                                  '.readonly': {}},
              'total_cost_calculated': {'.cli_option': {},
                                        '.drf_field': {},
                                        '.field': {},
                                        '.float': {},
                                        '.readonly': {}},
              # 'total_cost_manual': {'.cli_option': {},
                                    # '.drf_field': {},
                                    # '.field': {},
                                    # '.float': {}},
              # 'total_cost_change_reason': {'.cli_option': {},
                                           # '.drf_field': {},
                                           # '.field': {},
                                           # '.string': {}},
              'travel_files': {'.cli_option': {},
                               '.drf_field': {},
                               '.field': {},
                               '.file': {},
                               '.readonly': {}},
              'travel_report': {'.cli_option': {},
                                '.drf_field': {},
                                '.field': {},
                                '.string': {}},
              'trip_days_after': {'.cli_option': {},
                                  '.drf_field': {},
                                  '.field': {},
                                  '.integer': {},
                                  '.readonly': {}},
              'trip_days_before': {'.cli_option': {},
                                   '.drf_field': {},
                                   '.field': {},
                                   '.integer': {},
                                   '.readonly': {}},
              'user': {'.cli_option': {},
                       '.drf_field': {},
                       '.field': {},
                       '.ref': {'to': 'api/users'},
                       '.required': {}},
              'user_recommendation': {'.cli_option': {},
                                      '.drf_field': {},
                                      '.field': {},
                                      '.string': {}}},
        '.drf_collection':
        {'authentication_classes':
         ['rest_framework.authentication.SessionAuthentication',
          'rest_framework.authentication.TokenAuthentication'],
         'mixins': ['texpenses.views.mixins.SecretaryCompensationMixin'],
         'model': 'texpenses.models.SecretaryCompensation',
         'model_serializers':
             ['texpenses.serializers.mixins.PetitionMixin'],
             'ordering_fields': ['id'],
             'permission_classes':
             ['rest_framework.permissions.IsAuthenticated',
              'rest_framework.permissions.DjangoModelPermissions'],
             'search_fields': ['first_name',
                               'last_name',
                               ]}}
