es:
  image: elasticsearch:2.4.0
  ports:
    - "9200:9200"
  environment:
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
kibana:
  image: kibana:4.6.4
  ports:
    - "5601:5601"
  links:
    - es
  environment:
    - ELASTICSEARCH_URL=http://es:9200
